<a href="https://colab.research.google.com/github/gumdropsteve/intro_to_python/blob/main/day_07/01_pandas_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

a = 'https://gist.githubusercontent.com/gumdropsteve/9fa0b65a8db5910567a7a945c679b18b/raw/cc329f0e3b7466df256a41064c4d142ccc0bd9ac/alaska_sample.csv'

df = pd.read_csv(a)

df

                                   url  ... ski_in_ski_out_bool
0    https://airbnb.com/rooms/47478213  ...                 NaN
1    https://airbnb.com/rooms/36840361  ...                 NaN
2    https://airbnb.com/rooms/31854993  ...                 NaN
3    https://airbnb.com/rooms/33910426  ...                 NaN
4    https://airbnb.com/rooms/43518723  ...                 NaN
..                                 ...  ...                 ...
295  https://airbnb.com/rooms/18716557  ...                 NaN
296   https://airbnb.com/rooms/2959878  ...                 NaN
297  https://airbnb.com/rooms/30048549  ...                 NaN
298   https://airbnb.com/rooms/6079463  ...                 NaN
299   https://airbnb.com/rooms/3363559  ...                 NaN

[300 rows x 33 columns]

In [4]:
df.head()

                                 url  ... ski_in_ski_out_bool
0  https://airbnb.com/rooms/47478213  ...                 NaN
1  https://airbnb.com/rooms/36840361  ...                 NaN
2  https://airbnb.com/rooms/31854993  ...                 NaN
3  https://airbnb.com/rooms/33910426  ...                 NaN
4  https://airbnb.com/rooms/43518723  ...                 NaN

[5 rows x 33 columns]

In [7]:
df.head(15)

                                  url  ... ski_in_ski_out_bool
0   https://airbnb.com/rooms/47478213  ...                 NaN
1   https://airbnb.com/rooms/36840361  ...                 NaN
2   https://airbnb.com/rooms/31854993  ...                 NaN
3   https://airbnb.com/rooms/33910426  ...                 NaN
4   https://airbnb.com/rooms/43518723  ...                 NaN
5   https://airbnb.com/rooms/31697765  ...                 NaN
6   https://airbnb.com/rooms/19144530  ...                 NaN
7   https://airbnb.com/rooms/16000074  ...                 NaN
8    https://airbnb.com/rooms/5794087  ...                 NaN
9   https://airbnb.com/rooms/19298976  ...                 NaN
10  https://airbnb.com/rooms/10601669  ...                 NaN
11  https://airbnb.com/rooms/39068592  ...                 NaN
12  https://airbnb.com/rooms/47499618  ...                 NaN
13  https://airbnb.com/rooms/34183577  ...                 NaN
14  https://airbnb.com/rooms/37429407  ...                 NaN

[15 rows x 33 columns]

In [8]:
df.tail()

                                   url  ... ski_in_ski_out_bool
295  https://airbnb.com/rooms/18716557  ...                 NaN
296   https://airbnb.com/rooms/2959878  ...                 NaN
297  https://airbnb.com/rooms/30048549  ...                 NaN
298   https://airbnb.com/rooms/6079463  ...                 NaN
299   https://airbnb.com/rooms/3363559  ...                 NaN

[5 rows x 33 columns]

In [9]:
df.sample(5)

                                   url  ... ski_in_ski_out_bool
140  https://airbnb.com/rooms/17806804  ...                 NaN
228  https://airbnb.com/rooms/46448997  ...                 NaN
70   https://airbnb.com/rooms/41131953  ...                 NaN
31   https://airbnb.com/rooms/23991017  ...                 NaN
69   https://airbnb.com/rooms/32241663  ...                 NaN

[5 rows x 33 columns]

In [10]:
df.sample()

                                  url  ... ski_in_ski_out_bool
14  https://airbnb.com/rooms/37429407  ...                 NaN

[1 rows x 33 columns]

In [11]:
df['url']

0      https://airbnb.com/rooms/47478213
1      https://airbnb.com/rooms/36840361
2      https://airbnb.com/rooms/31854993
3      https://airbnb.com/rooms/33910426
4      https://airbnb.com/rooms/43518723
                     ...
295    https://airbnb.com/rooms/18716557
296     https://airbnb.com/rooms/2959878
297    https://airbnb.com/rooms/30048549
298     https://airbnb.com/rooms/6079463
299     https://airbnb.com/rooms/3363559
Name: url, Length: 300, dtype: object

In [12]:
df.url

0      https://airbnb.com/rooms/47478213
1      https://airbnb.com/rooms/36840361
2      https://airbnb.com/rooms/31854993
3      https://airbnb.com/rooms/33910426
4      https://airbnb.com/rooms/43518723
                     ...
295    https://airbnb.com/rooms/18716557
296     https://airbnb.com/rooms/2959878
297    https://airbnb.com/rooms/30048549
298     https://airbnb.com/rooms/6079463
299     https://airbnb.com/rooms/3363559
Name: url, Length: 300, dtype: object

In [16]:
len(df['type'].unique())

23

In [17]:
df['type'].unique()

array(['Entire cabin', 'Entire chalet', 'Entire guesthouse',
       'Entire house', 'Entire apartment', 'Yurt', 'Entire condominium',
       'Entire guest suite', 'Farm stay', 'Tiny house', 'Dome house',
       'Entire cottage', 'Entire bungalow', 'Hostel beds', 'Private room',
       'Entire loft', 'Hotel room', 'Treehouse', 'Room', 'Hostel room',
       'Entire townhouse', 'Entire serviced apartment', 'Island'],
      dtype=object)

In [20]:
df['type'] == 'Island'

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Name: type, Length: 300, dtype: bool

In [21]:
import numpy as np

np.sum(df['type'] == 'Island')

1

In [28]:
df.loc[df['type'] == 'Island']

                                   url  ... ski_in_ski_out_bool
250  https://airbnb.com/rooms/16660817  ...                 NaN

[1 rows x 33 columns]

In [26]:
df[df['type'] == 'Island']

                                   url  ... ski_in_ski_out_bool
250  https://airbnb.com/rooms/16660817  ...                 NaN

[1 rows x 33 columns]

In [29]:
df.loc[df['type'] == 'Island'].url

250    https://airbnb.com/rooms/16660817
Name: url, dtype: object

In [30]:
df.loc[df['type'] == 'Island']['url']

250    https://airbnb.com/rooms/16660817
Name: url, dtype: object

## Getting Summary Info

In [32]:
type(df)

pandas.core.frame.DataFrame

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url                    300 non-null    object
 1   title                  300 non-null    object
 2   type                   300 non-null    object
 3   location               300 non-null    object
 4   guests                 174 non-null    float64
 5   bedrooms               300 non-null    int64
 6   beds                   174 non-null    float64
 7   is_studio              300 non-null    bool
 8   baths                  253 non-null    float64
 9   half_baths             24 non-null     float64
 10  shared_baths           6 non-null      float64
 11  price                  300 non-null    float64
 12  avg_rating             278 non-null    float64
 13  n_reviews              278 non-null    float64
 14  gym_bool               1 non-null      object
 15  wifi_bool              226 non-null    object
 16  self_check_in_bool     64 non-null     object
 17  air_conditioning_bool  6 non-null      object
 18  pets_allowed_bool      43 non-null     object
 19  indoor_fireplace_bool  13 non-null     object
 20  hot_tub_bool           13 non-null     object
 21  free_parking_bool      286 non-null    object
 22  pool_bool              0 non-null      float64
 23  kitchen_bool           226 non-null    object
 24  breakfast_bool         21 non-null     object
 25  elevator_bool          0 non-null      float64
 26  washer_bool            21 non-null     object
 27  dryer_bool             9 non-null      object
 28  heating_bool           133 non-null    object
 29  waterfront_bool        10 non-null     object
 30  dishwasher_bool        1 non-null      object
 31  beachfront_bool        9 non-null      object
 32  ski_in_ski_out_bool    6 non-null      object
dtypes: bool(1), float64(10), int64(1), object(21)
memory usage: 75.4+ KB

In [33]:
df.gym_bool

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
295    NaN
296    NaN
297    NaN
298    NaN
299    NaN
Name: gym_bool, Length: 300, dtype: object

In [36]:
df.gym_bool.fillna(False, inplace=True)

In [37]:
df.gym_bool

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Name: gym_bool, Length: 300, dtype: bool

#### .describe()
```
Generate descriptive statistics.

Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding NaN values.

Analyzes both numeric and object series, as well
as DataFrame column sets of mixed data types. The output
will vary depending on what is provided. Refer to the notes
below for more detail.
```

In [44]:
df.describe()

           guests    bedrooms        beds  ...   n_reviews  pool_bool  elevator_bool
count  174.000000  300.000000  174.000000  ...  278.000000        0.0            0.0
mean     2.873563    1.173333    2.873563  ...   74.953237        NaN            NaN
std      1.537994    0.916199    1.537994  ...   75.371532        NaN            NaN
min      0.000000    0.000000    0.000000  ...    3.000000        NaN            NaN
25%      2.000000    1.000000    2.000000  ...   20.500000        NaN            NaN
50%      2.000000    1.000000    2.000000  ...   54.500000        NaN            NaN
75%      3.000000    2.000000    3.000000  ...   99.250000        NaN            NaN
max     14.000000    6.000000   14.000000  ...  411.000000        NaN            NaN

[8 rows x 11 columns]

In [46]:
import numpy as np

np.mean(df['bedrooms'])

1.1733333333333333

In [47]:
np.mean(df['bedrooms']), np.max(df['bedrooms']), np.min(df['bedrooms'])

(1.1733333333333333, 6, 0)

In [52]:
np.sum(df['guests'].fillna(1)) / np.sum(df['bedrooms'])

1.7784090909090908

In [55]:
df['price'] / df['bedrooms'].replace(0, 1)

0       60.0
1       64.0
2       75.0
3      111.0
4      130.0
       ...
295    135.0
296     50.0
297     19.0
298    121.0
299     74.5
Length: 300, dtype: float64

In [56]:
df['guests'].fillna(1) / df['bedrooms'].replace(0, 1)

0      2.0
1      1.0
2      2.0
3      2.0
4      1.0
      ...
295    1.0
296    1.0
297    1.0
298    1.0
299    1.5
Length: 300, dtype: float64

In [57]:
np.mean(df['guests'].fillna(1) / df['bedrooms'].replace(0, 1))

1.528111111111111